# Generated by Django 2.2.10 on 2020-03-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('liens', models.URLField()),
                ('icones', models.ImageField(upload_to='', verbose_name=[('facebook', 'fab fa-facebook'), ('linkedin', 'fab fa-linkedin'), ('instagram', 'fab fa-instagram'), ('googleplus', 'fab fa-googleplus')])),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'compte social',
                'verbose_name_plural': 'compte socials',
            },
        ),
        migrations.CreateModel(
            name='Infosite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('mapurl', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'info site',
                'verbose_name_plural': 'info sites',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('video', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'presentation',
                'verbose_name_plural': 'presentation',
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('prenom', models.CharField(max_length=225)),
                ('photo', models.ImageField(upload_to='')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'temoignage',
                'verbose_name_plural': 'temoignages',
            },
        ),
    ]
